apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: {{ .Values.endpointServiceName }}-iap
spec:
  iap:
    enabled: true
    oauthclientCredentials:
      secretName: {{ .Values.oauthSecretName }}