apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: {{ template "iap-ingress.fullname" . }}
spec:
  iap:
    enabled: true
    oauthclientCredentials:
      secretName: {{ .Values.oauthSecretName }}