apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.endpointServiceName }}-esp
  labels:
    app: {{ template "iap-ingress.name" . }}
    chart: {{ template "iap-ingress.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Values.endpointServiceName }}-esp
rules:
- apiGroups: ["ctl.isla.solutions"]
  resources: ["cloudendpoints"]
  verbs: ["get", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Values.endpointServiceName }}-esp
  labels:
    app: {{ template "iap-ingress.name" . }}
    chart: {{ template "iap-ingress.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.endpointServiceName }}-esp
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Values.endpointServiceName }}-esp
  apiGroup: rbac.authorization.k8s.io