apiVersion: v1
description: NFS Server deployment for Kubernetes
name: nfs-server
version: 0.1.0
appVersion: 0.8
home: http://nfs.sourceforge.net/
sources:
- https://github.com/kubernetes/examples/tree/master/staging/volumes/
icon: https://www.linoxide.com/wp-content/uploads/2012/09/nfs_version.jpg
maintainers:
- name: danisla
  email: disla@google.com