# Default values for cloud-endpoints-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

cloudSA:
  enabled: false
  secretName:
  secretKey:

image:
  repository: gcr.io/cloud-solutions-group/cloud-endpoints-controller
  tag: 0.2.0
  pullPolicy: IfNotPresent