# Default values for cloud-endpoints-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

cloudSA:
  enabled: false
  secretName:
  secretKey:

godev:
  enabled: false
  gopath: github.com/danisla/cloud-endpoints-controller
  persistence:
    enabled: true
    size: 10Gi
    nfsHost: godev-nfs-nfs-server.metacontroller.svc.cluster.local
    nfsPath: /exports

image:
  repository: gcr.io/cloud-solutions-group/cloud-endpoints-controller
  tag: 0.1.0
  pullPolicy: Always