# This is the same as Dockerfile, but skips `dep ensure`.
# It assumes you already ran that locally.
FROM golang:1.10-alpine AS build

COPY . /go/src/github.com/danisla/cloud-endpoints-controller/
WORKDIR /go/src/github.com/danisla/cloud-endpoints-controller/cmd/cloud-endpoints-controller
RUN go install

FROM alpine:3.7
RUN apk add --update ca-certificates bash curl
COPY --from=build /go/bin/cloud-endpoints-controller /usr/bin/
CMD ["/usr/bin/cloud-endpoints-controller"]