apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "kube-metacontroller.fullname" . }}
  labels:
    app: {{ template "kube-metacontroller.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "kube-metacontroller.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "kube-metacontroller.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["/usr/bin/metacontroller"]
          args:
            - --logtostderr
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}