apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: initializercontrollers.metacontroller.k8s.io
  labels:
    app: {{ template "kube-metacontroller.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  group: metacontroller.k8s.io
  version: v1alpha1
  scope: Cluster
  names:
    plural: initializercontrollers
    singular: initializercontroller
    kind: InitializerController
    shortNames:
    - ic
    - ictl