apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cloudendpoints.ctl.isla.solutions
spec:
  group: ctl.isla.solutions
  version: v1
  scope: Namespaced
  names:
    plural: cloudendpoints
    singular: cloudendpoint
    kind: CloudEndpoint
    shortNames: ["cloudep", "ce"]
---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: cloud-endpoints-controller
spec:
  generateSelector: true
  resyncPeriodSeconds: 2
  parentResource:
    apiVersion: ctl.isla.solutions/v1
    resource: cloudendpoints
  childResources: []
  hooks:
    sync:
      webhook:
        url: http://cloud-endpoints-controller.metacontroller/sync
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cloud-endpoints-controller
  namespace: metacontroller
  labels:
    app: cloud-endpoints-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-endpoints-controller
  template:
    metadata:
      labels:
        app: cloud-endpoints-controller
    spec:
      serviceAccountName: cloud-endpoints-controller
      containers:
      - name: cloud-endpoints-controller
        image: gcr.io/cloud-solutions-group/cloud-endpoints-controller:0.2.1
        command: ["/usr/bin/cloud-endpoints-controller"]
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-endpoints-controller
  namespace: metacontroller
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
  selector:
    app: cloud-endpoints-controller
  
