apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-endpoints-controller
  namespace: metacontroller
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cloud-endpoints-controller
subjects:
- kind: ServiceAccount
  name: cloud-endpoints-controller
  namespace: metacontroller
roleRef:
  kind: ClusterRole
  name: cloud-endpoints-controller
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cloud-endpoints-controller
  namespace: metacontroller
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["services"]
  verbs: ["get", "list"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "list"]