{{- if .Values.envoy.enabled -}}
{{- if not .Values.envoy.configMapName -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.endpointServiceName }}-envoy-config
  labels:
    app: {{ template "iap-ingress.name" . }}
    chart: {{ template "iap-ingress.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  envoy-config.yaml: |
    admin:
      access_log_path: /tmp/admin_access.log
      address:
        socket_address: { address: 127.0.0.1, port_value: 9901 }
    
    static_resources:
      listeners:
      - name: ingress
        address:
          socket_address: { address: 0.0.0.0, port_value: 8080 }
        filter_chains:
        - filters:
          - name: envoy.http_connection_manager
            config:
              codec_type: AUTO
              stat_prefix: ingress_http
              route_config:
                name: local_route
                virtual_hosts:
                - name: upstream
                  domains: ["*"]
                  routes:
                  - match:
                      prefix: "/healthz"
                    route:
                      cluster: healthz
                      prefix_rewrite: /server_info
                      timeout: 10s
                  - match:
                      prefix: "/"
                    route:
                      cluster: upstream
                      timeout: 10s
                      upgrade_configs:
                      - upgrade_type: websocket
              
              http_filters:
              - name: envoy.filters.http.jwt_authn
                config:
                  providers:
                    jwt_auth:
                        issuer: "{{ .Values.envoy.jwtIssuer }}"
                        audiences: ["{JWT_AUDIENCE}"]
                        from_headers:
                        - name: {{ .Values.envoy.jwtHeaders }}
                        remote_jwks:
                          http_uri:
                            uri: "{{ .Values.envoy.jwksURI }}"
                            cluster: jwks
                          cache_duration:
                            seconds: 300
                  
                  rules:
                  - match:
                      prefix: /server_info
                  - match:
                      prefix: /healthz
                  - match:
                      prefix: /
                    requires:
                      provider_name: jwt_auth

              - name: envoy.router

              access_log:
              - name: envoy.file_access_log
                config:
                  path: /dev/fd/1

      clusters:
      - name: healthz
        connect_timeout: 0.25s
        type: STRICT_DNS
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: healthz
          endpoints:
          - lb_endpoints:
            - endpoint:
                address: 
                  socket_address:
                    protocol: TCP
                    address: 127.0.0.1
                    port_value: 9901
      
      - name: jwks
        connect_timeout: 0.25s
        type: LOGICAL_DNS
        dns_lookup_family: V4_ONLY
        circuit_breakers:
          thresholds:
            max_pending_requests: 10000
            max_requests: 10000
        lb_policy: ROUND_ROBIN
        tls_context: { sni: www.gstatic.com }
        load_assignment:
          cluster_name: jwks
          endpoints:
          - lb_endpoints:
            - endpoint:
                address: 
                  socket_address:
                    protocol: TCP
                    address: gstatic.com
                    port_value: 443
  
      - name: upstream
        connect_timeout: 0.25s
        type: STRICT_DNS
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: upstream
          endpoints:
          - lb_endpoints:
            - endpoint:
                address: 
                  socket_address:
                    protocol: TCP
                    address:  {{ .Values.targetServiceName }}.{{ .Release.Namespace }}
                    port_value: {{ .Values.targetServicePort }}
    
{{- end }}
{{- end }}