apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "cloud-endpoints-controller.fullname" . }}
  labels:
    app: {{ template "cloud-endpoints-controller.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: cloud-endpoints-controller
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: cloud-endpoints-controller
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        component: cloud-endpoints-controller
    spec:
      serviceAccountName: {{ template "cloud-endpoints-controller.fullname" . }}
      terminationGracePeriodSeconds: 5
      containers:
      - name: cloud-endpoints-controller
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ default "" .Values.image.pullPolicy | quote }}
        env:
        {{- if .Values.cloudSA.enabled }}
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/run/secrets/sa/{{ .Values.cloudSA.secretKey }}
        {{- end }}
        volumeMounts:
        {{- if .Values.cloudSA.enabled }}
        - name: sa-key
          readOnly: true
          mountPath: /var/run/secrets/sa
        {{- end }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
            scheme: HTTP
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2
      volumes:
      {{- if .Values.cloudSA.enabled }}
      - name: sa-key
        secret:
          secretName: {{ .Values.cloudSA.secretName }}
      {{- end }}