apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "nfs-server.fullname" . }}
  labels:
    app: {{ template "nfs-server.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "nfs-server.name" . }}
        release: {{ .Release.Name }}
        component: nfs-server
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            privileged: true
          ports:
            - name: nfs
              containerPort: 2049
            - name: mountd
              containerPort: 20048
            - name: rpcbind
              containerPort: 111
          volumeMounts:
            - name: persist
              mountPath: /exports
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
      volumes:
        - name: persist
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ template "nfs-server.fullname" . }}
        {{- else }}
          emptyDir: {}
        {{- end }}